name: Verible linter example
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: chipsalliance/verible-linter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}